version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.8 # Choose the appropriate Python version

jobs:
  test:
    executor: python-executor
    steps:
      - checkout  # Checkout the source code
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Selenium Test
          command: |
            python demo.py

workflows:
  version: 2
  test:
    jobs:
      - test
